### PR TITLE
AddSection support in Projects

### PR DESCRIPTION
**Pull request by diakoptis**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694718843648/427314554619905)

### CODE REVIEW

**Comment by diakoptis** [comment]
I run the tests before the PR and was OK (46 tests, 103 assertions)

Anyone knows what is the problem with Travis and the supported PHPUnit version error?

**Comment by praecipula** [comment]
Hey, thanks @diakoptis for your PR!

I'm not sure why the build is failing - I'll have to take a dig into it when we can next examine things; we definitely were passing before, but it's only failing on the hhvm version of PHP 🤔 

When it comes to creating a section in a project, our convention is to have a function called `createInProject` on a `SectionsBase` resource. You can see that we have this resource in the branch that gets autogenerated by our tools (https://github.com/Asana/php-asana/blob/api-meta-incoming/src/Asana/Resources/Gen/SectionsBase.php#L28), but haven't gotten to doing the rest of what's needed to pull this into the master branch :/

The general idea of what needs to happen is to work in the branch called "api-meta-incoming" (https://github.com/Asana/php-asana/tree/api-meta-incoming). It has the autogenerated files from our documentation with stubs for new resources; the remaining work is to subclass the new resource's base class in https://github.com/Asana/php-asana/tree/api-meta-incoming/src/Asana/Resources/Gen with the new subclass in https://github.com/Asana/php-asana/tree/api-meta-incoming/src/Asana/Resources and add the new resource to https://github.com/Asana/php-asana/blob/master/src/Asana/Client.php#L54, and create tests in https://github.com/Asana/php-asana/blob/api-meta-incoming/tests/Asana/ResourcesTest.php (which badly needs a refactor anyway :/) Hopefully that makes sense.

Sorry it's been so long since this library got some love, but we're talking about ways to make the overhead of updating our 6 client libraries smaller in the future. I'm hopeful that we'll be able to prioritize a pass on them sooner rather than later!

**Comment by diakoptis** [comment]
Hey @praecipula, 

Thank you for your response. It's now clear to me. I didn't notice the branches. I'm sorry for any inconvenience and I hope I didn't waste your valuable time :)

(ps. This is my first PR and I'm really glad I did it, even though it was not ok. Thank you again for your patience)

**Comment by joetrollo** [comment]
This was added as part of a bulk update in #53

**Pull request closed without merging**
